/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserViewPanel.java
 *
 * Created on 13.01.2012, 19:34:29
 */

package de.versatel.noc.vsafe.server.mvc.views;

/**
 *
 * @author ulrich.stemmer
 */
public class UserViewPanel extends javax.swing.JPanel {

    /** Creates new form UserViewPanel */
    public UserViewPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_N = new javax.swing.JPanel();
        jLabel_Username = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jButton_Edit = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel_CN = new javax.swing.JPanel();
        jLabel_Usergroup = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jPanelCenter = new javax.swing.JPanel();
        jComboBox_Usergroup = new javax.swing.JComboBox();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_FirstName = new javax.swing.JTextField();
        jPasswordField_1 = new javax.swing.JPasswordField();
        jButton_ResetPW = new javax.swing.JButton();
        jPanelSouth = new javax.swing.JPanel();
        jPanel_CS = new javax.swing.JPanel();
        jLabel_State = new javax.swing.JLabel();
        jComboBox_State = new javax.swing.JComboBox();
        jLabel_ActWrongLogins = new javax.swing.JLabel();
        jTextField_ActWrongLogins = new javax.swing.JTextField();
        jLabel_MaxWrongLogins = new javax.swing.JLabel();
        jTextField_MaxWrongLogins = new javax.swing.JTextField();
        jLabel_MaxSessions = new javax.swing.JLabel();
        jTextField_MaxSessions = new javax.swing.JTextField();
        jLabel_SessionTimeout = new javax.swing.JLabel();
        jTextField_SessionTimeout = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel_S = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton_Apply = new javax.swing.JButton();
        jButton_OK = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jPanel_N.setLayout(new java.awt.GridBagLayout());

        jLabel_Username.setText("Benutzername:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel_N.add(jLabel_Username, gridBagConstraints);

        jTextField_Username.setEnabled(false);
        jTextField_Username.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextField_Username.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel_N.add(jTextField_Username, gridBagConstraints);

        jButton_Edit.setText("bearbeiten");
        jButton_Edit.setToolTipText("bearbeiten");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel_N.add(jButton_Edit, gridBagConstraints);

        jButton_Add.setText("Neuer Benutzer");
        jButton_Add.setToolTipText("Neuer Benutzer");
        jButton_Add.setMaximumSize(new java.awt.Dimension(120, 23));
        jButton_Add.setMinimumSize(new java.awt.Dimension(120, 23));
        jButton_Add.setPreferredSize(new java.awt.Dimension(120, 23));
        jButton_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_AddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_AddMousePressed(evt);
            }
        });
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel_N.add(jButton_Add, gridBagConstraints);

        jButton_Delete.setText("Lösche Benutzer");
        jButton_Delete.setToolTipText("Lösche Benutzer");
        jButton_Delete.setMaximumSize(new java.awt.Dimension(120, 23));
        jButton_Delete.setMinimumSize(new java.awt.Dimension(120, 23));
        jButton_Delete.setPreferredSize(new java.awt.Dimension(120, 23));
        jButton_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_DeleteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_DeleteMousePressed(evt);
            }
        });
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel_N.add(jButton_Delete, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel_N.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel_N, gridBagConstraints);

        jPanel_CN.setBorder(javax.swing.BorderFactory.createTitledBorder("Benutzereinstellungen"));
        jPanel_CN.setLayout(new java.awt.GridBagLayout());

        jLabel_Usergroup.setText("Benutzergruppe:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel_CN.add(jLabel_Usergroup, gridBagConstraints);

        jLabel_Name.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        jPanel_CN.add(jLabel_Name, gridBagConstraints);

        jLabel_FirstName.setText("Vorname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        jPanel_CN.add(jLabel_FirstName, gridBagConstraints);

        jLabel_Password.setText("Passwort:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 10, 0);
        jPanel_CN.add(jLabel_Password, gridBagConstraints);

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel_CN.add(jPanelCenter, gridBagConstraints);

        jComboBox_Usergroup.setMinimumSize(new java.awt.Dimension(120, 20));
        jComboBox_Usergroup.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        jPanel_CN.add(jComboBox_Usergroup, gridBagConstraints);

        jTextField_Name.setMinimumSize(new java.awt.Dimension(120, 20));
        jTextField_Name.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        jPanel_CN.add(jTextField_Name, gridBagConstraints);

        jTextField_FirstName.setMinimumSize(new java.awt.Dimension(120, 20));
        jTextField_FirstName.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        jPanel_CN.add(jTextField_FirstName, gridBagConstraints);

        jPasswordField_1.setText("jPasswordField1");
        jPasswordField_1.setMinimumSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 10, 0);
        jPanel_CN.add(jPasswordField_1, gridBagConstraints);

        jButton_ResetPW.setText("Neues Passwort");
        jButton_ResetPW.setToolTipText("Neues Passwort");
        jButton_ResetPW.setPreferredSize(new java.awt.Dimension(120, 24));
        jButton_ResetPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetPWActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 10, 0);
        jPanel_CN.add(jButton_ResetPW, gridBagConstraints);

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weighty = 1.0;
        jPanel_CN.add(jPanelSouth, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        add(jPanel_CN, gridBagConstraints);

        jPanel_CS.setBorder(javax.swing.BorderFactory.createTitledBorder("Session Einstellungen"));
        jPanel_CS.setLayout(new java.awt.GridBagLayout());

        jLabel_State.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel_CS.add(jLabel_State, gridBagConstraints);

        jComboBox_State.setMinimumSize(new java.awt.Dimension(120, 20));
        jComboBox_State.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel_CS.add(jComboBox_State, gridBagConstraints);

        jLabel_ActWrongLogins.setText("Anzahl fehlerhafter Logins:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel_CS.add(jLabel_ActWrongLogins, gridBagConstraints);

        jTextField_ActWrongLogins.setEditable(false);
        jTextField_ActWrongLogins.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField_ActWrongLogins.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel_CS.add(jTextField_ActWrongLogins, gridBagConstraints);

        jLabel_MaxWrongLogins.setText("Anzahl max. fehlerh. Logins:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel_CS.add(jLabel_MaxWrongLogins, gridBagConstraints);

        jTextField_MaxWrongLogins.setMinimumSize(new java.awt.Dimension(120, 20));
        jTextField_MaxWrongLogins.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel_CS.add(jTextField_MaxWrongLogins, gridBagConstraints);

        jLabel_MaxSessions.setText("Anzahl gleichzeitiger Sessions:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel_CS.add(jLabel_MaxSessions, gridBagConstraints);

        jTextField_MaxSessions.setMinimumSize(new java.awt.Dimension(120, 20));
        jTextField_MaxSessions.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel_CS.add(jTextField_MaxSessions, gridBagConstraints);

        jLabel_SessionTimeout.setText("Session Timeout:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel_CS.add(jLabel_SessionTimeout, gridBagConstraints);

        jTextField_SessionTimeout.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField_SessionTimeout.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel_CS.add(jTextField_SessionTimeout, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel_CS.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        add(jPanel_CS, gridBagConstraints);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel5, gridBagConstraints);

        jPanel_S.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel_S.add(jPanel6, gridBagConstraints);

        jButton_Apply.setText("Übernehmen");
        jButton_Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ApplyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 10, 0);
        jPanel_S.add(jButton_Apply, gridBagConstraints);

        jButton_OK.setText("Ok");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 10, 10);
        jPanel_S.add(jButton_OK, gridBagConstraints);

        jButton_Cancel.setText("Abbrechen");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 10, 0);
        jPanel_S.add(jButton_Cancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jPanel_S, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddMouseEntered
        // TODO add your handling code here:
}//GEN-LAST:event_jButton_AddMouseEntered

    private void jButton_AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddMouseExited
        // TODO add your handling code here:
}//GEN-LAST:event_jButton_AddMouseExited

    private void jButton_AddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddMousePressed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton_AddMousePressed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
}//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DeleteMouseEntered
        // TODO add your handling code here:
}//GEN-LAST:event_jButton_DeleteMouseEntered

    private void jButton_DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DeleteMouseExited
        // TODO add your handling code here:
}//GEN-LAST:event_jButton_DeleteMouseExited

    private void jButton_DeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DeleteMousePressed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton_DeleteMousePressed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
}//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ApplyActionPerformed
}//GEN-LAST:event_jButton_ApplyActionPerformed

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
}//GEN-LAST:event_jButton_OKActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed

}//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_ResetPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetPWActionPerformed

}//GEN-LAST:event_jButton_ResetPWActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Apply;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JButton jButton_ResetPW;
    private javax.swing.JComboBox jComboBox_State;
    private javax.swing.JComboBox jComboBox_Usergroup;
    private javax.swing.JLabel jLabel_ActWrongLogins;
    private javax.swing.JLabel jLabel_FirstName;
    private javax.swing.JLabel jLabel_MaxSessions;
    private javax.swing.JLabel jLabel_MaxWrongLogins;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_SessionTimeout;
    private javax.swing.JLabel jLabel_State;
    private javax.swing.JLabel jLabel_Usergroup;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPanel jPanel_CN;
    private javax.swing.JPanel jPanel_CS;
    private javax.swing.JPanel jPanel_N;
    private javax.swing.JPanel jPanel_S;
    private javax.swing.JPasswordField jPasswordField_1;
    private javax.swing.JTextField jTextField_ActWrongLogins;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_MaxSessions;
    private javax.swing.JTextField jTextField_MaxWrongLogins;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_SessionTimeout;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables

}
