/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserControlTreeViewPanel.java
 *
 * Created on 03.01.2012, 04:52:32
 */

package de.versatel.noc.vsafe.server.mvc.views;

/**
 *
 * @author ulrich.stemmer
 */
public class UserControlTreeViewPanel extends javax.swing.JPanel {

    /** Creates new form UserControlTreeViewPanel */
    public UserControlTreeViewPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_UserControl = new javax.swing.JTree();
        jPanel_Details = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(jTree_UserControl);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout jPanel_DetailsLayout = new javax.swing.GroupLayout(jPanel_Details);
        jPanel_Details.setLayout(jPanel_DetailsLayout);
        jPanel_DetailsLayout.setHorizontalGroup(
            jPanel_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        jPanel_DetailsLayout.setVerticalGroup(
            jPanel_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel_Details);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_Details;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree_UserControl;
    // End of variables declaration//GEN-END:variables

}
