/*
 * FrameStart.java
 *
 * Created on 07.02.2011, 23:50:02
 *
 *
 * Rot (Hausfarbe) 	RGB 232,017,017
 * Weiß			RGB 255,255,255
 * Grau			RGB 135,136,138
 * Schwarz 		RGB 0,0,0
 */
package de.versatel.noc.vsafe.server.gui;

/**
 *
 * @author ulrich.stemmer
 */
import de.versatel.noc.vsafe.shared.core.settings.SystemSettings;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author ulrich.stemmer
 */
public class FrameStart extends javax.swing.JFrame {


    static final String SUPERUSER = "su";
    static final String SUPERPASSWORT = "su";
    private GuiHandling guiHandling;

    public FrameStart(GuiHandling guiHandling) {
        this.guiHandling = guiHandling;
        initComponents();
        jProgressBar1.setVisible(true);
        jLabel_Message.setVisible(true);

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(
                (d.width - getSize().width) / 2,
                (d.height - getSize().height) / 2);
        setIconImage(guiHandling.getApplicationIcon().getImage());
        setTitle(SystemSettings.APPLICATION_TITLE);
        setVisible(true);
    }

    public void setStartMessage(String message){
    if (message != null){
        jLabel_Message.setText(message);

        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabelImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel_Message = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setName("frameStart"); // NOI18N
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(400, 280));
        jLayeredPane1.setRequestFocusEnabled(false);

        jLabelImage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelImage.setMaximumSize(new java.awt.Dimension(400, 280));
        jLabelImage.setMinimumSize(new java.awt.Dimension(400, 280));
        jLabelImage.setPreferredSize(new java.awt.Dimension(400, 280));
        jLabelImage.setBounds(0, 0, 400, 280);
        jLayeredPane1.add(jLabelImage, javax.swing.JLayeredPane.PALETTE_LAYER);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 280));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 280));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 280));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(232, 17, 17));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Versatel NOC VSafe");
        jLabelTitle.setFocusable(false);
        jLabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jLabelTitle, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(152, 85, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel1.setBounds(0, 0, 400, 280);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.NORTH);

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(400, 20));

        jLabel_Message.setText("jLabel_Message");
        jLabel_Message.setMaximumSize(new java.awt.Dimension(400, 20));
        jLabel_Message.setMinimumSize(new java.awt.Dimension(400, 20));
        jLabel_Message.setPreferredSize(new java.awt.Dimension(400, 20));
        jLabel_Message.setBounds(0, 0, 400, 20);
        jLayeredPane2.add(jLabel_Message, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jProgressBar1.setForeground(new java.awt.Color(232, 17, 17));
        jProgressBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jProgressBar1.setMaximumSize(new java.awt.Dimension(400, 20));
        jProgressBar1.setMinimumSize(new java.awt.Dimension(400, 20));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(400, 20));
        jProgressBar1.setBounds(0, 0, 400, 20);
        jLayeredPane2.add(jProgressBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabel_Message;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
