/*
 * IFrameNewUser.java
 *
 * Created on 12.02.2011, 21:39:01
 */
package de.versatel.noc.vsafe.server.gui;

/**
 *
 * @author ulrich.stemmer
 */
import de.versatel.noc.vSafe_Server.users.User;
import de.versatel.noc.vSafe_Server.users.UserGroup;
import de.versatel.noc.vSafe_Server.users.UserStates;
import de.versatel.noc.vSafe_Server.bl.*;

/**
 *
 * @author ulrich.stemmer
 */
public class IFrameNewUser extends javax.swing.JInternalFrame {

    private FrameMain frameMain;
    private IFrameUserControl iFrameUserManagement;

    //private String[] newUserNames;
    /** Creates new form IFrameNewUser */
    public IFrameNewUser() {
        initComponents();
    }

    /** Creates new form Server_NewUser
     * @param iFrameUserManagement
     */
    public IFrameNewUser(IFrameUserControl iFrameUserManagement) {
        initComponents();
        this.iFrameUserManagement = iFrameUserManagement;
        this.frameMain = iFrameUserManagement.frameMain;
    }

    private void clearFields() {
        this.jTextField_Username.setText("");
        this.jTextField_Password.setText("");
        this.jTextField_Name.setText("");
        this.jTextField_Firstname.setText("");
        this.jTextField_SessionTimeout.setText("");

        this.jComboBox_MaxSessions.setSelectedIndex(0);
        this.jComboBox_MaxWrongLogins.setSelectedIndex(0);
        this.jComboBox_Usergroup.setSelectedIndex(0);
    }

    private void apply() {
        String s = "Sollen die Eingaben Übernommen werden ?";
        int i = javax.swing.JOptionPane.showConfirmDialog(this.getContentPane(), s, getTitle()
                + "Frage", javax.swing.JOptionPane.YES_NO_OPTION);
        if (i == javax.swing.JOptionPane.YES_OPTION) {
            User user = new User();
            user.username.setValue(this.jTextField_Username.getText());
            Object o = jComboBox_Usergroup.getSelectedItem();
            if (o instanceof UserGroup) {
                UserGroup ug = (UserGroup) o;
                user.userGroupId.setValue(ug.userGroupId.getValue());
            } else {
                user.setUserGroupId(0);
            }

            user.setName(jTextField_Name.getText());
            user.setFirstname(jTextField_Firstname.getText());
            String cryptedPassword = frameMain.userHandling.
                    cryptUserPassword(this.jTextField_Password.getText());
            user.setPassword(cryptedPassword);
            user.setState(UserStates.NEWUSER);
            user.setActWrongLogins(0);
            user.setMaxWrongLogins((Integer) jComboBox_MaxWrongLogins.getSelectedItem());
            user.setMaxSessions((Integer) jComboBox_MaxSessions.getSelectedItem());
            long to = Long.parseLong(jTextField_SessionTimeout.getText()) * 60 * 1000;
            user.setSessionTimeout(to);

            if (frameMain.userHandling.addUser(user)) {
                /* Daten im uebergeordneten Fenster aktualisieren. */
                frameMain.iFrameUserManagement.jComboBox_Username.removeAllItems();
                for (User u : frameMain.userHandling.users) {
                    frameMain.iFrameUserManagement.jComboBox_Username.addItem(u);
                }
                frameMain.iFrameUserManagement.jComboBox_Username.setSelectedItem(user);
            } else {
                String t = "Daten konnten nicht geändert werden.";
                javax.swing.JOptionPane.showMessageDialog(this.getContentPane(), t, "Fehler",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            iFrameUserManagement.setVisible(true);
        }
    }

    private void close() {
        this.dispose();
    }

    private void cancel() {
        String s = "Sollen die Eingaben verworfen werden ?";
        int i = javax.swing.JOptionPane.showConfirmDialog(this.getContentPane(), s, getTitle()
                + "Frage", javax.swing.JOptionPane.YES_NO_OPTION);
        if (i == javax.swing.JOptionPane.YES_OPTION) {
            iFrameUserManagement.setVisible(true);
            this.dispose();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_N = new javax.swing.JPanel();
        jLabel_Username = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_Username = new javax.swing.JTextField();
        jTextField_Password = new javax.swing.JTextField();
        jButton_getPassword = new javax.swing.JButton();
        jPanel_CN = new javax.swing.JPanel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Firstname = new javax.swing.JLabel();
        jLabel_State = new javax.swing.JLabel();
        jLabel_UserGroup = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Firstname = new javax.swing.JTextField();
        jComboBox_State = new javax.swing.JComboBox();
        jComboBox_Usergroup = new javax.swing.JComboBox();
        jPanel_CS = new javax.swing.JPanel();
        jLabel_MaxWrongLogins = new javax.swing.JLabel();
        jLabel_MaxSessions = new javax.swing.JLabel();
        jLabel_SessionTimeout = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox_MaxWrongLogins = new javax.swing.JComboBox();
        jComboBox_MaxSessions = new javax.swing.JComboBox();
        jTextField_SessionTimeout = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel_S = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Apply = new javax.swing.JButton();
        jButton_Ok = new javax.swing.JButton();

        setTitle("Neuer Benutzer");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel_N.setLayout(new java.awt.GridBagLayout());

        jLabel_Username.setText("Benutzername:");
        jLabel_Username.setMaximumSize(new java.awt.Dimension(73, 20));
        jLabel_Username.setMinimumSize(new java.awt.Dimension(73, 20));
        jLabel_Username.setPreferredSize(new java.awt.Dimension(73, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel_N.add(jLabel_Username, gridBagConstraints);

        jLabel_Password.setText("Passwort:");
        jLabel_Password.setMaximumSize(new java.awt.Dimension(48, 20));
        jLabel_Password.setMinimumSize(new java.awt.Dimension(48, 20));
        jLabel_Password.setPreferredSize(new java.awt.Dimension(48, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 10, 0);
        jPanel_N.add(jLabel_Password, gridBagConstraints);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 1.0;
        jPanel_N.add(jPanel3, gridBagConstraints);

        jTextField_Username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Username.setText("ulrich.stemmer");
        jTextField_Username.setMinimumSize(new java.awt.Dimension(200, 20));
        jTextField_Username.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel_N.add(jTextField_Username, gridBagConstraints);

        jTextField_Password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Password.setText("jTextField2");
        jTextField_Password.setMinimumSize(new java.awt.Dimension(120, 20));
        jTextField_Password.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 10, 0);
        jPanel_N.add(jTextField_Password, gridBagConstraints);

        jButton_getPassword.setText("Hole Passwort");
        jButton_getPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_getPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 10, 10);
        jPanel_N.add(jButton_getPassword, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel_N, gridBagConstraints);

        jPanel_CN.setBorder(javax.swing.BorderFactory.createTitledBorder("Benutzereinstellungen"));
        jPanel_CN.setLayout(new java.awt.GridBagLayout());

        jLabel_Name.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel_CN.add(jLabel_Name, gridBagConstraints);

        jLabel_Firstname.setText("Vorname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        jPanel_CN.add(jLabel_Firstname, gridBagConstraints);

        jLabel_State.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        jPanel_CN.add(jLabel_State, gridBagConstraints);

        jLabel_UserGroup.setText("Benutzergruppe:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 10, 0);
        jPanel_CN.add(jLabel_UserGroup, gridBagConstraints);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel_CN.add(jPanel4, gridBagConstraints);

        jTextField_Name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Name.setMinimumSize(new java.awt.Dimension(200, 20));
        jTextField_Name.setPreferredSize(new java.awt.Dimension(200, 20));
        jTextField_Name.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel_CN.add(jTextField_Name, gridBagConstraints);

        jTextField_Firstname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Firstname.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextField_Firstname.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 10);
        jPanel_CN.add(jTextField_Firstname, gridBagConstraints);

        jComboBox_State.setEnabled(false);
        jComboBox_State.setMinimumSize(new java.awt.Dimension(120, 20));
        jComboBox_State.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 10);
        jPanel_CN.add(jComboBox_State, gridBagConstraints);

        jComboBox_Usergroup.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 10, 10);
        jPanel_CN.add(jComboBox_Usergroup, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel_CN, gridBagConstraints);

        jPanel_CS.setBorder(javax.swing.BorderFactory.createTitledBorder("Sessioneinstellungen"));
        jPanel_CS.setLayout(new java.awt.GridBagLayout());

        jLabel_MaxWrongLogins.setText("Max. Anzahl fehlerhafter Anmeldungen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel_CS.add(jLabel_MaxWrongLogins, gridBagConstraints);

        jLabel_MaxSessions.setText("Anzahl gleichzeitiger Sessions:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 0, 0);
        jPanel_CS.add(jLabel_MaxSessions, gridBagConstraints);

        jLabel_SessionTimeout.setText("Session-Timeout:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 10, 10, 0);
        jPanel_CS.add(jLabel_SessionTimeout, gridBagConstraints);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel_CS.add(jPanel5, gridBagConstraints);

        jComboBox_MaxWrongLogins.setMinimumSize(new java.awt.Dimension(70, 20));
        jComboBox_MaxWrongLogins.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel_CS.add(jComboBox_MaxWrongLogins, gridBagConstraints);

        jComboBox_MaxSessions.setMinimumSize(new java.awt.Dimension(70, 20));
        jComboBox_MaxSessions.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 10);
        jPanel_CS.add(jComboBox_MaxSessions, gridBagConstraints);

        jTextField_SessionTimeout.setMinimumSize(new java.awt.Dimension(70, 20));
        jTextField_SessionTimeout.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 10, 10);
        jPanel_CS.add(jTextField_SessionTimeout, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel_CS, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel_S.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel_S.add(jPanel2, gridBagConstraints);

        jButton_Cancel.setText("Abbruch");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 10, 0);
        jPanel_S.add(jButton_Cancel, gridBagConstraints);

        jButton_Apply.setText("Übernehmen");
        jButton_Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ApplyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 10, 0);
        jPanel_S.add(jButton_Apply, gridBagConstraints);

        jButton_Ok.setText("OK");
        jButton_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 10, 10);
        jPanel_S.add(jButton_Ok, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(jPanel_S, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        cancel();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OkActionPerformed
        apply();
        close();
    }//GEN-LAST:event_jButton_OkActionPerformed

    private void jButton_getPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_getPasswordActionPerformed
        this.jTextField_Password.setText(frameMain.userHandling.generateUserPassword(8));
    }//GEN-LAST:event_jButton_getPasswordActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        iFrameUserManagement.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton_ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ApplyActionPerformed
        apply();
        clearFields();
    }//GEN-LAST:event_jButton_ApplyActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Apply;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Ok;
    private javax.swing.JButton jButton_getPassword;
    private javax.swing.JComboBox jComboBox_MaxSessions;
    private javax.swing.JComboBox jComboBox_MaxWrongLogins;
    private javax.swing.JComboBox jComboBox_State;
    private javax.swing.JComboBox jComboBox_Usergroup;
    private javax.swing.JLabel jLabel_Firstname;
    private javax.swing.JLabel jLabel_MaxSessions;
    private javax.swing.JLabel jLabel_MaxWrongLogins;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_SessionTimeout;
    private javax.swing.JLabel jLabel_State;
    private javax.swing.JLabel jLabel_UserGroup;
    private javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_CN;
    private javax.swing.JPanel jPanel_CS;
    private javax.swing.JPanel jPanel_N;
    private javax.swing.JPanel jPanel_S;
    private javax.swing.JTextField jTextField_Firstname;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Password;
    private javax.swing.JTextField jTextField_SessionTimeout;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
